{% set name = "polyfactory" %}
{% set version = "2.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/polyfactory-{{ version }}.tar.gz
  sha256: 099d86f7c79c51a2caaf7c8598cc56e7b0a57c11b5918ddf699e82380735b6b7

build:
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  number: 0
  skip: true  # [py<38]

requirements:
  host:
    - python 
    - hatchling
    - pip
  run:
    - python
    - faker
    - typing-extensions

{% set tests_to_skip = "" %} 
{% set tests_to_ignore = "" %}
# type error
{% set tests_to_ignore = tests_to_ignore + " --ignore=tests/test_recursive_models.py" %}
# OSError: Invalid argument
{% set tests_to_skip = tests_to_skip + " test_handle_constrained_date[ge-le]"%}
{% set tests_to_skip = tests_to_skip + " or test_handle_constrained_date[gt-lt]"%}
{% set tests_to_skip = tests_to_skip + " or test_handle_constrained_date[ge-lt]"%}
{% set tests_to_skip = tests_to_skip + " or test_handle_constrained_date[gt-le]"%}

test:
  source_files:
    - tests
  imports:
    - polyfactory
  commands:
      # skipping for osx due to pymongo platform tag error
    - pip check                                                             # [not osx]
    - pytest -v tests {{ tests_to_ignore }} -k "not ({{ tests_to_skip }})"  # [win]
    - pytest -v tests {{ tests_to_ignore }}                                 # [not win]
  requires:
    - pip
    - pytest
    - sqlalchemy
    - hypothesis
    - pydantic
    - bson
    - pymongo
    - aiosqlite
    - email_validator
    - annotated-types
    - msgspec

about:
  home: https://github.com/litestar-org/polyfactory
  summary: Mock data generation factories
  license: MIT
  license_file: LICENSE
  license_family: MIT
  description: |
    Polyfactory is a simple and powerful mock data generation library, based around type 
    hints and supporting dataclasses, typed-dicts, pydantic models, msgspec structs and more.
  dev_url: https://github.com/litestar-org/polyfactory
  doc_url: https://polyfactory.litestar.dev/
extra:
  recipe-maintainers:
    - ivergara
