{% set name = "polyfactory" %}
{% set version = "2.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/polyfactory-{{ version }}.tar.gz
  sha256: 099d86f7c79c51a2caaf7c8598cc56e7b0a57c11b5918ddf699e82380735b6b7

build:
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv 
  number: 0
  skip: true  # [py<38]

requirements:
  host:
    - python 
    - hatchling
    - pip
  run:
    - python 
    - faker
    - typing-extensions

test:
  imports:
    - polyfactory
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/litestar-org/polyfactory
  summary: Mock data generation factories
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ivergara
