{% set name = "polyfactory" %}
{% set version = "2.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/polyfactory-{{ version }}.tar.gz
  sha256: 26dc3a52baae1ebd6386708d9a99f8ea4ef57c9d45e556815ee5e44a1cd27fc0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - hatchling
    - pip
  run:
    - python >=3.8,<4.0
    - faker
    - typing-extensions

test:
  imports:
    - polyfactory
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/litestar-org/polyfactory
  summary: Mock data generation factories
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ivergara
