{% set name = "polyfactory" %}
{% set version = "3.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 237258b6ff43edf362ffd1f68086bb796466f786adfa002b0ac256dbf2246e9a

build:
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  number: 0
  skip: true  # [py<39 or s390x]

requirements:
  host:
    - python 
    - hatchling
    - pip
  run:
    - python
    - faker >=5.0.0
    - typing-extensions >=4.6.0
  run_constrained:
    - sqlalchemy >=1.4.29
    - attrs >=22.2.0
    - odmantic <1.0.0
    - msgspec >=0.20.0
    - pymongo <4.9
    - eval-type-backport >=0.2.2
    - pydantic >=1.10

{% set tests_to_skip = "" %} 
{% set tests_to_ignore = "" %}
# type error
{% set tests_to_ignore = tests_to_ignore + " --ignore=tests/test_recursive_models.py" %}
# OSError: Invalid argument
{% set tests_to_skip = tests_to_skip + " test_handle_constrained_date[ge-le]" %}
{% set tests_to_skip = tests_to_skip + " or test_handle_constrained_date[gt-lt]" %}
{% set tests_to_skip = tests_to_skip + " or test_handle_constrained_date[ge-lt]" %}
{% set tests_to_skip = tests_to_skip + " or test_handle_constrained_date[gt-le]" %}
# email_validator not up to date
{% set tests_to_skip = tests_to_skip + " or test_type_property_parsing" %}

test:
  source_files:
    - tests
  imports:
    - polyfactory
  commands:
    - pip check
    - pytest -v tests {{ tests_to_ignore }} -k "not ({{ tests_to_skip }})"            # [win]
    - pytest -v tests {{ tests_to_ignore }} -k "not test_type_property_parsing"       # [not win]
  requires:
    - pip
    - pytest
    - pytest-asyncio
    - sqlalchemy
    - hypothesis
    - pydantic
    - pymongo
    - aiosqlite
    - annotated-types
    - msgspec

about:
  home: https://github.com/litestar-org/polyfactory
  summary: Mock data generation factories
  license: MIT
  license_file: LICENSE
  license_family: MIT
  description: |
    Polyfactory is a simple and powerful mock data generation library, based around type 
    hints and supporting dataclasses, typed-dicts, pydantic models, msgspec structs and more.
  dev_url: https://github.com/litestar-org/polyfactory
  doc_url: https://polyfactory.litestar.dev/
extra:
  recipe-maintainers:
    - ivergara
